export const FETCH_TASK_LIST_SUCCESS = 'task/FETCH_TASK_LIST_SUCCESS';
export const CREATE_TASK_SUCCESS = 'task/CREATE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'task/UPDATE_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'task/DELETE_TASK_SUCCESS';

export const FETCH_BOARD_LIST_SUCCESS = 'board/FETCH_BOARD_LIST_SUCCESS';
export const CREATE_BOARD_SUCCESS = 'board/CREATE_BOARD_SUCCESS';
export const UPDATE_BOARD_SUCCESS = 'board/UPDATE_BOARD_SUCCESS';
export const DELETE_BOARD_SUCCESS = 'board/DELETE_BOARD_SUCCESS';
